name: tipsplit
description: A simple tip & bill split calculator with localized tipping norms and respectful ads.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  google_mobile_ads: ^5.1.0
  http: ^1.2.2
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/data/tipping_norms.json


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1

flutter_icons:
  android: true
  ios: true
  image_path: assets/branding/icon_1025.png
  adaptive_icon_background: "#3F51B5"
  adaptive_icon_foreground: assets/branding/logo_513.png

flutter_native_splash:
  color: "#F7F8FC"
  color_dark: "#121212"
  image: assets/branding/splash_logo_513.png
  android_12:
    color: "#F7F8FC"
    icon_background_color: "#F7F8FC"
    image: assets/branding/splash_logo_513.png
  ios: true
  android: true
